# Generated by Django 5.2.2 on 2025-06-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
    ]
