# Generated by Django 5.2.2 on 2025-06-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_alter_review_unique_together_review_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_people',
            new_name='guests',
        ),
    ]
